### PR TITLE
Fix highlight image rendering

### PR DESCRIPTION
**Pull request by jonandersen**

### CODE REVIEW

**Comment by jonandersen** [comment]
This PR fixes issue https://github.com/fulldecent/FDWaveformView/issues/101

**Comment by fulldecent** [comment]
Please rebase, I believe this is ready to merge after that. Thank you!

**Comment by jonandersen** [comment]
@fulldecent  Sorry for taking so long to update this, I've rebased. Let me know if all is good

**Comment by fulldecent** [comment]
Looks very good, thanks for sharing. Would you also please give yourself credit in CHANGELOG.md? And then this is ready to ship.

**Comment by jonandersen** [comment]
@fulldecent great, I've update the change log

**Comment by fulldecent** [comment]
Thank you, merged!

**Pull request merged**
