### PR TITLE
Swift 5 layout

### PR DESCRIPTION
**Pull request by yaroslav-zhurakovskiy**
Just want to be sure that I do everything correctly before jumping to other repositories. Here are some points:
- I added ".build" directory to ".gitignore". 
- I added ".swifpm" to ".gitignore".
- As far as I understand these libraries work only on iOS platform. They won't even compile for linux. Is there a need for Tests/LinuxMain.swift?
- As far as I understand codebase was written before Swift 5. There are some deprecated methods calls if to build using Swift 5, particularly unsafe memory pointers api.  You might want to upgrade to the newer codebase. I did not touch the codebase.
- Travic CI will probably break because there are no xcodeproject files any more. I don't know whether Travic CI started supporting Swift Packages. I have not checked yet. 
- CheckCocoaPodsQualityIndexes.rb does not work. I did not touch it.
- I have not been able to test unit tests without objective-c runtime. As far as I understand it is done only for linux...
- I don't understand why but "pod spec lint" does not find any source code files. I downloaded "FDChessboardView-master" and it tells me the same thing. I will look into it. I use 1.8.4 version.
- You might want to updated the template a little bit for Package.swift. You might want to change swift-tools-version to 5.0. Package has some new params like "platforms". As far as I understand this option allows Xcode 11 to integrate packages better. Also there is "swiftLanguageVersions" option.

### CODE REVIEW

**Comment by fulldecent** [comment]
Thank you. This is moving in the right direction.

- As far as I understand these libraries work only on iOS platform. They won't even compile for linux. Is there a need for Tests/LinuxMain.swift?

Yes, can keep LinuxMain as a failing test. Linux will become a supported platform in the future. Once we migrate to SwiftUI and Linux supports SwiftUI.

- As far as I understand codebase was written before Swift 5. There are some deprecated methods calls if to build using Swift 5, particularly unsafe memory pointers api.  You might want to upgrade to the newer codebase. I did not touch the codebase.

Please a new issue for this.

- Travic CI will probably break because there are no xcodeproject files any more. I don't know whether Travic CI started supporting Swift Packages. I have not checked yet. 

Please check Travis CI, you can see the results here above.

- CheckCocoaPodsQualityIndexes.rb does not work. I did not touch it.

We can remove that. Support for CocpaPods is deprecated.

- I have not been able to test unit tests without objective-c runtime. As far as I understand it is done only for linux...

Please create an issue explaining this so tests can be updated.

- I don't understand why but "pod spec lint" does not find any source code files. I downloaded "FDChessboardView-master" and it tells me the same thing. I will look into it. I use 1.8.4 version.

Thank you. Please create a separate issue for that. We can proceed with this PR even if CocoaPods does not work.

- You might want to updated the template a little bit for Package.swift. You might want to change swift-tools-version to 5.0. Package has some new params like "platforms". As far as I understand this option allows Xcode 11 to integrate packages better. Also there is "swiftLanguageVersions" option.

This is a great idea. Please create issues on the template project.

**Comment by yaroslav-zhurakovskiy** [comment]
I upgraded the codebase to Swift 5, fixed cocoapods and travis CI. I did not fix CheckCocoaPodsQualityIndexes so, I left it as it is. You might want to delete Carthage support from README.md. I think that is it, but I might be missing something.

**Comment by yaroslav-zhurakovskiy** [comment]
I have a question about swift versions. For FDWaveformView I set swift version as v5. Should it support just v5 or for example v5 and v4.2?

**Comment by fulldecent** [comment]
Looks great, thank you. I'll update the README now.

**Pull request merged**
