### PR TITLE
add optional func waveformViewWasTapped

### PR DESCRIPTION
**Pull request by jboegeholz**
to notify the delegate of the new position of the progress

### CODE REVIEW

**Comment by pixlwave** [comment]
For consistency, would it make sense to rename this to waveformViewWasScrubbed?

**Comment by pixlwave** [comment]
Just to elaborate, renaming would mean this delegate method could then be called on the scrub action at the end of the handlePanGesture function too.

**Comment by fulldecent** [comment]
I would prefer that clients use KVO to access the progress property if possible. Also this would extend naturally to clients wanting to know of zooming changes.

Is this way doable?

**Comment by jboegeholz** [comment]
I gave KVO a try and could retrieve updated values from the waveform after tapping. But I'm running into infinite loops because I set the progress while observing it.

**Comment by fulldecent** [comment]
Does this help:

http://stackoverflow.com/questions/14246537/kvo-infinite-recurrence-loop

**Comment by fulldecent** [comment]
OK, a lot has changed in the project recently. Progress is gone, highlighting is now a thing. (It is more generic than progress.)

So now this PR makes sense again. There is a merge conflict to correct. Also I'd like to consider the correct outcomes for the different scenarios of scrubbing etc. being turned on/off.

**Comment by pixlwave** [comment]
Just to add a follow-up on this, as far as I can tell this way is the required way to go in Swift 4.0 due to the following:

- KVO in Swift 4.0 using `object.observe(\.keyPath) { handler }` requires the variable to be marked as `dynamic`.
- A `dynamic` variable in Swift must be bridged to Objective-C with `@objc`.
- `hightlightedSamples` is of a type which cannot be represented in Objective-C.
- Making `progressSamples` dynamic works, however as it's a computed value the observation will never trigger.

I'd love to be proved wrong if I've missed something here.

**Comment by fulldecent** [comment]
Thank you, this feature is merged in #110.

**Pull request closed without merging**
