### PR TITLE
Fix a retain cycle in render operation closure

### PR DESCRIPTION
**Pull request by pjay**

### CODE REVIEW

**Comment by fulldecent** [comment]
Thank you for finding this. Could you please explain what situation this is fixing. And is there more documentation on this technique (since it is not immediately obvious to me).

**Comment by pjay** [comment]
The problem is that the view has a strong reference to the render operation (`inProgressWaveformRenderOperation`) and this operation also keeps a strong reference to the view (via its completion handler), hence the cycle. The view and the operation are never released because of this retain cycle. The capture list specifying `weak self` breaks this cycle and the `strongSelf` dance ensures the view still exists when the render operation is finished and calls its completion handler.  I noticed this issue in an app that was dealing with large waveform views, 100's of MBs of waveform data were cached and never released, which crashes the app quite quickly.

There is some info on this type of issue in the [Swift Programming Language guide](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AutomaticReferenceCounting.html#//apple_ref/doc/uid/TP40014097-CH20-ID56). The `self`/`strongSelf` dance is common when dealing with such issues (there is an example of it in the README of Alamofire).

**Comment by fulldecent** [comment]
Beautiful, thank you!

For reference:

- https://github.com/Alamofire/Alamofire/issues/1551
- https://github.com/Alamofire/Alamofire/commit/32b0ae9c9baea52d6db7249836ad102b516c46df

**Comment by fulldecent** [comment]
Released in 2.2.1. Thanks again!

**Pull request merged**
